<div class="clear"></div>
<?php do_action('CMPOPFLY_show_messages'); ?>
<?php
if( !empty($messages) ):
    foreach($messages as $message):
        ?><div class="updated"><p><?php echo $message; ?></p></div><?php
    endforeach;
endif;
?>
<?php require('statistics/top.phtml'); ?>

<br>
<h1>PRO plan offers:</h1>
<p style="font-size:16px; max-width:72%;">The admin dashboard provides detailed statistics and performance data for your popups. Monitor the effectiveness of each campaign, conduct A/B tests, and identify which popup achieves better conversion rates.</p>
<br>
<div style="float:left; width:100%; margin-bottom:30px;">
<div style="text-align:center; width:300px; float:left; margin-right:20px;">
<a href="<?php echo plugins_url('../assets/images/01_statistics_daily_report.png', __FILE__); ?>" target="_blank" style="text-decoration:none;">
	<img src="<?php echo plugins_url('../assets/images/01_statistics_daily_report.png', __FILE__); ?>" alt="" style="width:100%; border:1px solid #444;" />
</a>
<span style="font-size:15px;">Daily Report</span>
</div>
<div style="text-align:center; width:300px; float:left; margin-right:20px;">
<a href="<?php echo plugins_url('../assets/images/02_statistics_report_by_period.png', __FILE__); ?>" target="_blank" style="text-decoration:none;">
	<img src="<?php echo plugins_url('../assets/images/02_statistics_report_by_period.png', __FILE__); ?>" alt="" style="width:100%; border:1px solid #444;" />
</a>
<span style="font-size:15px;">Report by Period</span>
</div>
<div style="text-align:center; width:300px; float:left; margin-right:20px;">
<a href="<?php echo plugins_url('../assets/images/03_statistics_access_log.png', __FILE__); ?>" target="_blank" style="text-decoration:none;">
	<img src="<?php echo plugins_url('../assets/images/03_statistics_access_log.png', __FILE__); ?>" alt="" style="width:100%; border:1px solid #444;" />
</a>
<span style="font-size:15px;">Access Log</span>
</div>
</div>
<br>
<h3>Upgrade to Pro for:</h3>
<ul style="font-size:16px;">
<li><svg data-slot="icon" aria-hidden="true" fill="none" stroke-width="1.5" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" style="color:#008000; width:15px;"><path d="M12 4.5v15m7.5-7.5h-15" stroke-linecap="round" stroke-linejoin="round"></path></svg> Detailed popup performance insights</li>
<li><svg data-slot="icon" aria-hidden="true" fill="none" stroke-width="1.5" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" style="color:#008000; width:15px;"><path d="M12 4.5v15m7.5-7.5h-15" stroke-linecap="round" stroke-linejoin="round"></path></svg> Easy tracking of conversion rates</li>
<li><svg data-slot="icon" aria-hidden="true" fill="none" stroke-width="1.5" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" style="color:#008000; width:15px;"><path d="M12 4.5v15m7.5-7.5h-15" stroke-linecap="round" stroke-linejoin="round"></path></svg> Customizable reporting options</li>
<li><svg data-slot="icon" aria-hidden="true" fill="none" stroke-width="1.5" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" style="color:#008000; width:15px;"><path d="M12 4.5v15m7.5-7.5h-15" stroke-linecap="round" stroke-linejoin="round"></path></svg> Visual graphs for quick data analysis</li>
<li><svg data-slot="icon" aria-hidden="true" fill="none" stroke-width="1.5" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" style="color:#008000; width:15px;"><path d="M12 4.5v15m7.5-7.5h-15" stroke-linecap="round" stroke-linejoin="round"></path></svg> Identifies top-performing campaigns</li>
<li><svg data-slot="icon" aria-hidden="true" fill="none" stroke-width="1.5" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" style="color:#008000; width:15px;"><path d="M12 4.5v15m7.5-7.5h-15" stroke-linecap="round" stroke-linejoin="round"></path></svg> Real-time performance updates</li>
</ul>
<br>
<a href="<?php echo admin_url('admin.php?page=cmpopfly_pro'); ?>" style="font-size: 16px; line-height: 20px; font-weight: 500; padding: 10px 30px; background-color: #008000; border-color: #008000; color: #fff; text-decoration:none;">Upgrade to Pro</a>